-- Active: 1771331834330@@127.0.0.1@5432@jlpt

-- CREATE DATABASE jlpt;

-- Wipe all Tables
-- DROP TABLE Deck_Vocabulary;
-- DROP TABLE Decks;
-- DROP TABLE User_Vocab_Flags;
-- DROP TABLE User_Vocab_Progress;
-- DROP TABLE Users;
DROP TABLE Vocabulary;

-- Core Tables
CREATE TABLE IF NOT EXISTS Vocabulary(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    kanji VARCHAR,
    furigana VARCHAR,
    english VARCHAR,
    jlpt_level INT,
    UNIQUE (kanji, furigana)
);

-- ALTER TABLE Vocabulary ADD CONSTRAINT unique_kanji UNIQUE (kanji);
-- ALTER TABLE Vocabulary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE TABLE IF NOT EXISTS Users(
    id GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR,
    hashed_password VARCHAR,
    created_at DATE DEFAULT CURRENT_DATE
);

-- ALTER TABLE Users ALTER COLUMN created_at SET DEFAULT CURRENT_DATE

CREATE TABLE IF NOT EXISTS  User_Vocab_Progress(
    id GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES Users (id),
    vocab_id INT REFERENCES Vocabulary (id),
    correct_count INT,
    incorrect_count INT,
    last_reviewed_at DATE DEFAULT CURRENT_DATE,
    next_review_at DATE
)

-- ALTER TABLE User_Vocab_Progress ALTER COLUMN last_reviewed_at SET DEFAULT CURRENT_DATE

-- Flags
CREATE TABLE IF NOT EXISTS  User_Vocab_Flags(
    user_id INT REFERENCES Users (id),
    vocab_id INT REFERENCES Vocabulary (id),
    is_favorite BOOLEAN,
    is_ignored BOOLEAN,
    PRIMARY KEY (user_id, vocab_id)
)

-- Decks
CREATE TABLE IF NOT EXISTS  Decks(
    id GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES Users (id),
    deck_name VARCHAR,
    created_at DATE DEFAULT CURRENT_DATE
)

-- ALTER TABLE Decks ALTER COLUMN created_at SET DEFAULT CURRENT_DATE

CREATE TABLE IF NOT EXISTS  Deck_Vocabulary(
    deck_id INT REFERENCES Decks (id),
    vocab_id INT REFERENCES Vocabulary (id),
    PRIMARY KEY (deck_id, vocab_id)
)